### PR TITLE
Added api auth to all post/put routes in the api.

### PR DESCRIPTION
**Pull request by angaither**
#### What's this PR do?
it does the thing that's in the title
`POST` and `PUT` routes require an api key now. 

#### How should this be reviewed?
- can you send a `POST` request without keys? nope? GOOD 

#### Any background context you want to provide?
I have still have to build the corresponding phoenix work for this

#### Relevant tickets
Fixes #https://trello.com/c/uJssCEtG/100-as-a-developer-i-want-to-create-an-authenticating-api-request-for-rogue-users-3-of-3

#### Checklist
- [x] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by sbsmith86** [comment]
woot!

**Comment by sbsmith86** [comment]
@angaither Oh one question. How do we go about generating real keys for all the environments?

**Comment by angaither** [comment]
@sbsmith86 I'll generate them & add them to each environment 😄

**Comment by sbsmith86** [comment]
👍

**Pull request merged**
