### PR TITLE
Add forge

### PR DESCRIPTION
**Pull request by sbsmith86**
#### What's this PR do?

Adds the Forge pattern library to Rogue using our shared webpack config.

#### Any background context you want to provide?

We now have a homepage with VERY IMPORTANT CONTENT 

image

#### Relevant tickets
Addresses #1

### CODE REVIEW

**Comment by DFurnes** [comment]
Looks like a bunch of Forge files got committed in the `public/assets/vendor`. 😬 Looks like there's some (varyingly complicated haha) solutions for this [in this StackOverflow](http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore).

**Comment by sbsmith86** [comment]
@DFurnes I knoooowwwwwws i updated the gitignore too late. lemme see what i can do.

**Comment by sbsmith86** [comment]
@DFurnes fixed!!!

**Comment by DFurnes** [comment]
Looks great! 🚢

**Pull request merged**
