### PR TITLE
Moves review gate to Posts Controller to allow script to bulk approve

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
Moves review gate to Posts Controller to allow script to bulk approve. Also, per @DFurnes 's comment below, this logic should actually live in the Posts Controller anyway since the repository should really only be responsible for storing or retrieving data.

#### How should this be reviewed?
👀 

#### Relevant tickets
References change made [here](https://github.com/DoSomething/rogue/pull/859/commits/7533ec2513919d7ecebb5670397a5c66cb1206c6). 

Needed for [this](https://www.pivotaltracker.com/n/projects/2019429/stories/165090581) Pivotal Card.
#### How to deploy
https://github.com/DoSomething/rogue/blob/master/docs/development/deployments.md

### CODE REVIEW

**Comment by chloealee** [comment]
hmm the `testNonStaffUpdatePost` test fails with this new line since phpunit is run from the console. I'm not sure how to get around this with the new code. Looking for potentially another way to determine that this is run in a job instead of using `app()->runningInConsole()` to check this?

**Comment by chloealee** [comment]
@DFurnes I think it is important to keep this unit test here but having a hard time deciding on a different way then using `app()->runningInConsole()` here! Two other ideas that aren't great but leaning towards the second option as the way to go:

1. Have the Bulk Review Script hit an API endpoint with machine token instead of using the Post Repositories [update](https://github.com/DoSomething/rogue/blob/master/app/Console/Commands/BulkReviewPosts.php#L78) method. 
2. Creating a new method in the Post Repository (maybe named `bulkReviewPosts`) that skips over the [gate check logic](https://github.com/DoSomething/rogue/blob/master/app/Repositories/PostRepository.php#L174-L176) so it can update posts? 

I like the second option better because it seems a little weird to have a job run inside of Rogue to hit it's own endpoint? Thoughts on this?

**Comment by chloealee** [comment]
OR - is it ok to mark this test as incomplete for now, just while I run the bulk approval job? Campaign leads need to have these reviewed by EOD tomorrow!

**Comment by DFurnes** [comment]
@chloealee Riffing off your second suggestion, can we move the gate logic out into the controller, since it's only relevant to web requests? The repository should really only be responsible for storing or retrieving data.

**Comment by chloealee** [comment]
@DFurnes Love that suggestion - so smart! Updated :)

**Pull request merged**
