### PR TITLE
Updates internal campaign name placeholder to mimic naming convention 

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
Updates internal campaign name placeholder to mimic naming convention outlined in [this doc](https://docs.google.com/document/d/1wIShshIhs9X6XEj1nUE1ZRcaRh9J52uyc8tqwQbMP7o/edit#).
screen shot 2018-12-05 at 5 14 49 pm

#### How should this be reviewed?
👀 

#### How to deploy
https://github.com/DoSomething/rogue/blob/master/docs/development/deployments.md

### CODE REVIEW

**Comment by chloealee** [comment]
@ngjo your instructions on how to create a campaign in Rogue inspired me to put in the naming convention as a helper! LMK if this looks ok to you!

**Comment by chloealee** [comment]
@ngjo oh that is right! I'll merge this for now and happy to change it in the future too to be under the text box! I imagine we'd probably want more details in the descriptor under the text box so think it makes sense to wait for that language before pulling out but that is easy to do!

**Comment by chloealee** [comment]
@ngjo oh that is right! I'll merge this for now and happy to change it in the future too to be under the text box! I imagine we'd probably want more details in the descriptor under the text box so think it makes sense to wait for that language before pulling out but that is easy to do!

**Comment by DFurnes** [comment]
@ngjo @chloealee Yeah, I think that's a good call – placeholders should have example text, and help text should be listed as a "footnote" below the field, like we do on forms in Aurora:

screen shot 2018-12-06 at 11 32 23 am

**Pull request merged**
