### PR TITLE
Add support for using ImageMagick on Heroku.

### PR DESCRIPTION
**Pull request by DFurnes**
#### What's this PR do?
This pull request adds a `IMAGE_DRIVER` environment variable, and instructs Heroku to install the [ImageMagick PHP extension](http://php.net/manual/en/book.imagick.php) so we can test out `IMAGE_DRIVER = imagick` there.

#### How should this be reviewed?
👀

#### Any background context you want to provide?
Switching to use ImageMagick on Heroku should provide a good performance boost when resizing/cropping images, which will help us more efficiently handle larger image uploads.

#### Relevant tickets
N/A

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by sheyd** [comment]
🥇 📈 🥃

**Comment by DFurnes** [comment]
One downside is that this would require `ext-imagick` to be installed on Homestead boxes as well for Compose commands not to complain (since that has to be listed as an app dependency for it to get installed on the Heroku dyno). It's something we can always handle in `after.sh`, but still a lil' bummer:

```sh
# after.sh

sudo apt-get update
sudo apt-get install -y php-imagick
sudo service php7.0-fpm restart
```

**Comment by sheyd** [comment]
That...kind of sucks. 👿

**Comment by DFurnes** [comment]
We had tested deploying this directly to Thor before break and it didn't seem to have a noticeable performance improvement. I'm going to close this for now since it doesn't seem worth complicating our dev environments without a real payoff.

**Pull request closed without merging**
