### PR TITLE
drops unique key in reactions table for northstar_user

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
Drops the unique key in the `reactions` table for the `northstar_user` column.

#### How should this be reviewed?
👀 

#### Any background context you want to provide?
When we renamed the table from `kudos` to `reactions` we forgot to drop indexes (more info. [here](https://dosomething.slack.com/?redir=%2Farchives%2FC0YGXUE01%2Fp1493318041448517))

We need to fix this for Reactions to work when Rogue is powering the Phoenix-Ashes gallery to allow a user to react to more than one post. https://github.com/DoSomething/phoenix/pull/7366

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by chloealee** [comment]
I'm not sure why previous commits were added to this PR? Those should already be merged!

**Comment by chloealee** [comment]
Since those changes are already merged into the `master` branch, is it ok to just keep in this PR?

**Comment by sbsmith86** [comment]
@chloealee  did you rebase?

**Comment by chloealee** [comment]
@sbsmith86 I did! @katiecrane suggested (and I think she is right) what might have happened is that I accidentally branched off another branch instead of master

**Comment by DFurnes** [comment]
Can you `git rebase -i HEAD~8` to get these out of here? They have different commit hashes than the ones merged into `master` so it might be weird otherwise (for example, 4d9450014d7cc0b560acb7c3ca8a34e00754e90b vs. 4c2f29369f8c00f1d485c3bbb31be09c54377433)

**Comment by chloealee** [comment]
ooh thanks @DFurnes ! Should I just squash all of those commits and only pick the ones that are new?

**Comment by DFurnes** [comment]
Yep! You should be able to either type `drop` or just delete the lines for the commits you don't want.

**Comment by chloealee** [comment]
yay awesome - thanks so much @DFurnes !

**Pull request merged**
