### PR TITLE
Updated the the product slack channel name

### PR DESCRIPTION
**Pull request by mirie**
Change the help message from #team-product to #help-product

### CODE REVIEW

**Comment by ngjo** [comment]
Jumping on this, can we also revise "Logging in will allow you to review and search for reportbacks." to something like: "Logging in will give you access to member submissions and campaign/action IDs."

**Comment by DFurnes** [comment]
@ngjo Mmmm, that makes good sense to me.

**Comment by mirie** [comment]
@ngjo Updated that help text as well!

**Comment by mirie** [comment]
Hello! Just pinging for a review so that I can merge or make updates!

**Pull request merged**
