### PR TITLE
Blank state if there are no events to show in the History Modal

### PR DESCRIPTION
**Pull request by katiecrane**
#### What's this PR do?
If there are no events under a signup, instead of not opening the history modal at all (which means there would be no way to update quantity either), show a blank state!

Blank:
image

Not blank:
image

#### How should this be reviewed?
Does it look okay? Is the copy okay?

#### Relevant tickets
[Card](https://www.pivotaltracker.com/story/show/152851215)

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by chloealee** [comment]
@katiecrane This looks good! I _thought_ that we always took the first event and put it in the history modal but now looking at the code, we might have changed that? Do we still want that logic to always include the first even in the history log? If not, this looks great! And maybe we should just remove this in the [comment](https://github.com/DoSomething/rogue/blob/master/resources/assets/components/HistoryModal/index.js#L39-L40) so it's not confusing?

**Comment by katiecrane** [comment]
@chloealee oooo I didn't change anything about which events were included. This PR is to handle the modal not crashing when there are NO events so in that case we can't take the first one. It looks like the chunk that you linked to is original to [The History Log PR ](https://github.com/DoSomething/rogue/pull/439) (with some spaces added with a linting fix) so I don't think any of the logic has actually changed?

**Comment by chloealee** [comment]
@katiecrane ah okay! Yeah I was trying to see if there was a fix but maybe I was just off when I wrote that bc looking at that code, it doesn't actually look like we're grabbing the first one if there is only one... 

Another thing I'm trying to think through though - isn't there always an event with a signup? When a signup is created, doesn't it trigger an event?

**Comment by katiecrane** [comment]
@chloealee Sorry I'm confused what you were trying to find a fix for?

I think there was some case on Thor where the events didn't exist? This is just to protect us in edge cases like that and hopefully won't ever see the light of day! But in those cases I don't think we want to block updating quantity/have the modal completely not open due to an error.

**Comment by chloealee** [comment]
Sry! I meant a fix / change to the logic to always grab the first event and add it to the history modal. Maybe I just didn't write it correctly to do that in the first place though bc now that code is confusing me! 

That makes sense to me for the edge cases!

**Comment by katiecrane** [comment]
@chloealee ahh I get it now! Do you think we should add a card to look into that?

**Comment by chloealee** [comment]
@katiecrane I'm not sure if it is _that_ big of a deal, especially since we're eventually going to re-do the events system/table?

**Pull request merged**
