### PR TITLE
add a readme to the documentation folder

### PR DESCRIPTION
**Pull request by angaither**
#### What's this PR do?
add a readme to the doc folder

#### How should this be reviewed?
👓 

#### Any background context you want to provide?
it's much easier to read when it's all in one place

#### Relevant tickets
Fixes #🎨

### CODE REVIEW

**Comment by sbsmith86** [comment]
I imagine this file getting kinda crazy once the API gets built out more.

**Comment by angaither** [comment]
@sbsmith86 yeah, but it's even crazier not to have a page where you can see how to use the API

**Comment by sbsmith86** [comment]
ok

**Comment by angaither** [comment]
ok.

**Comment by sbsmith86** [comment]
I meant ok 👍 lol my b

**Pull request merged**
