### PR TITLE
Always return signup when updating a signup or creating another post for a signup

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
- Always return a signup when updating a signup or creating another post for a signup so it is consistent. 

#### How should this be reviewed?
👀 

#### Relevant tickets
Fixes this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151852854)

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by sbsmith86** [comment]
@DFurnes are you sure we don't need to check with sergii on this? I feel like if we always send the `signup`  blink will not register RBs that get created when a user updates their quantity or why participated.

**Comment by chloealee** [comment]
(working on the tests and figuring out why wercker is failing!)

**Comment by DFurnes** [comment]
> @DFurnes are you sure we don't need to check with sergii on this? I feel like if we always send the `signup`  blink will not register RBs that get created when a user updates their quantity or why participated. 

Ahhh @sbsmith86 you're right, this would definitely cause Blink issues. Maybe the quick fix is to just add an `&& $postOrSignup instanceof Post` to the feature flag conditional here, and we can refactor this in the repository later on.

**Comment by chloealee** [comment]
hmm @DFurnes when I do that check to see if it is an `instanceof Post`, it says false because this is what `$data` is at that point: 
```

.array:15 [
  "northstar_id" => "56d9f70da59dbf176b8b45d2"
  "campaign_id" => 1283
  "campaign_run_id" => 1343
  "quantity" => 108
  "why_participated" => "Inventore voluptates adipisci iure aliquam doloremque magni minima. Voluptas cum sit qui. Eaque dolores dolor est laborum accusantium nisi dolorem."
  "num_participants" => null
  "caption" => "Consequatur voluptate laudantium fugiat soluta eos possimus sed."
  "source" => "phpunit"
  "remote_addr" => "143.141.209.63"
  "crop_x" => 0
  "crop_y" => 0
  "crop_width" => 100
  "crop_height" => 100
  "crop_rotate" => 90
  "file" => Illuminate\Http\Testing\File {#1187
    +name: "photo.jpg"
    +tempFile: stream resource {@930
      timed_out: false
      blocked: true
      eof: false
      wrapper_type: "plainfile"
      stream_type: "STDIO"
      mode: "r+b"
      unread_bytes: 0
      seekable: true
      uri: "/tmp/phpOkHSzP"
      options: []
    }
    +sizeToReport: null
    -test: true
    -originalName: "photo.jpg"
    -mimeType: "image/jpeg"
    -size: 91
    -error: 0
    #hashName: null
    path: "/tmp"
    filename: "phpOkHSzP"
    basename: "phpOkHSzP"
    pathname: "/tmp/phpOkHSzP"
    extension: ""
    realPath: "/tmp/phpOkHSzP"
    aTime: 2017-10-10 20:48:27
    mTime: 2017-10-10 20:48:27
    cTime: 2017-10-10 20:48:27
    inode: 922388
    size: 91
    perms: 0100600
    owner: 1000
    group: 1000
    type: "file"
    writable: true
    readable: true
    executable: false
    file: true
    dir: false
    link: false
  }
]
```

**Comment by chloealee** [comment]
One thing that I'm still confused by is why it's just saying it received an `id` instead of `signup_id` when we dumped things out in the terminal @DFurnes ? The [Signup Transformer](https://github.com/DoSomething/rogue/blob/master/app/Http/Transformers/SignupTransformer.php#L49) (and `https://github.com/DoSomething/rogue/blob/master/app/Http/Transformers/PostTransformer.php#L36`) should both return `signup_id`...

**Comment by DFurnes** [comment]
I think the `id` was coming [from the `toBlinkPayload`](https://github.com/DoSomething/rogue/blob/67b3cf8be475c9ca2a09adb0cb61de6de9c13bb8/app/Models/Signup.php#L92-L110) "transformer" on the model.

**Comment by chloealee** [comment]
oo thanks for clarifying, @DFurnes !

**Comment by chloealee** [comment]
thank you for all the help @DFurnes and @sbsmith86 ! This is now passing all the tests! 🎉

**Pull request merged**
