### PR TITLE
Add migrate

### PR DESCRIPTION
**Pull request by blisteringherb**
#### What's this PR do?
I've fixed the issue that was preventing `php artisan migrate` from running

#### How should this be reviewed?
This branch with the changes has been deployed to Rogue via Jenkins here - https://jenkins.dosomething.org/view/All/job/Rogue%20Deployment/38/console  

The `npm run build` task is temporarily commented out because it was causing the following error both in dev and production:  

Is `npm run build` still the correct command to run?  
```
> @ build /home/vagrant/sites/rogue
> npm run clean && npm run modernizr && NODE_ENV=production webpack


> @ clean /home/vagrant/sites/rogue
> rm -rf public/dist


> @ modernizr /home/vagrant/sites/rogue
> modernizr -c node_modules/@dosomething/forge/modernizr.json -d public/dist/modernizr.js

sh: 1: modernizr: not found

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "modernizr"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ modernizr: `modernizr -c node_modules/@dosomething/forge/modernizr.json -d public/dist/modernizr.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ modernizr script 'modernizr -c node_modules/@dosomething/forge/modernizr.json -d public/dist/modernizr.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     modernizr -c node_modules/@dosomething/forge/modernizr.json -d public/dist/modernizr.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/sites/rogue/npm-debug.log

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run clean && npm run modernizr && NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'npm run clean && npm run modernizr && NODE_ENV=production webpack'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run modernizr && NODE_ENV=production webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/sites/rogue/npm-debug.log
```

#### Relevant tickets
Fixes https://github.com/DoSomething/devops/issues/214

#### Checklist
- [x] Tested on staging.

### CODE REVIEW

**Comment by sbsmith86** [comment]
Thanks Morgan!

**Comment by sbsmith86** [comment]
@blisteringherb I chatted with @DFurnes in Slack and from him 

```
[1:05]  
On production right now you’re running `npm install —production` and `npm run build`.

[1:05]  
It should be `npm install` and `npm run build`.

[1:06]  
By running `npm install —production` on Jenkins, you’re skipping over the dev dependencies that are necessary for running the build script.
```

So we just need to remove the `--production` flag on that `npm install` command

**Comment by blisteringherb** [comment]
@sbsmith86 This is GTG now. The deploy is running successfully with both `php artisan migrate` and `npm run build`.   https://jenkins.dosomething.org/view/All/job/Rogue%20Deployment/40/console

**Comment by sbsmith86** [comment]
@blisteringherb Sweet, thanks!

**Pull request merged**
