### PR TITLE
upgrades just-extend and runs composer update

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
upgrades `just-extend` and runs `composer update` per [this](https://github.com/dosomething/rogue/network/alert/package-lock.json/just-extend/open) Github security alert. 

#### How should this be reviewed?
👀 

#### How to deploy
https://github.com/DoSomething/rogue/blob/master/docs/development/deployments.md

### CODE REVIEW

**Comment by chloealee** [comment]
I updated `just-extend` to be `"just-extend": ">=4.0.0",` but should that be `"just-extend": "^4.0.0",` instead?

**Comment by DFurnes** [comment]
> I updated `just-extend` to be `"just-extend": ">=4.0.0",` but should that be `"just-extend": "^4.0.0",` instead?

Where did you change this?

**Comment by chloealee** [comment]
In the `package-lock.json` file per the suggestion in the alert!

**Comment by DFurnes** [comment]
Ah! It's probably not a wise idea to manually edit our `package-lock.json`, since those changes will be reverted next time someone installs a package using the CLI (and it's not a super friendly file to work with).

Since this is a sub-dependency, and [it's been updated upstream](https://github.com/sinonjs/nise/blob/242c9504b4a058ef10d849d14147f10ad303f474/package.json#L63), you should be able to just re-generate the lockfile to grab this and any other updated dependencies:

```
rm -rf node_modules package-lock.json
npm install
```

**Comment by DFurnes** [comment]
> I updated `just-extend` to be `"just-extend": ">=4.0.0",` but should that be `"just-extend": "^4.0.0",` instead?

For your original question, yes! We'd definitely prefer `^4.0.0`, since `>=4.0.0` would pull in _anything_ that's a greater version number, including potentially breaking changes in `5.x.x` or `6.x.x`, etc.

**Comment by chloealee** [comment]
> Ah! It's probably not a wise idea to manually edit our package-lock.json, since those changes will be reverted next time someone installs a package using the CLI (and it's not a super friendly file to work with).
Since this is a sub-dependency, and it's been updated upstream, you should be able to just re-generate the lockfile to grab this and any other updated dependencies:
rm -rf node_modules package-lock.json
npm install

Super helpful to know for the future, thank you @DFurnes ! Updated with what you suggested. I ran it outside of my vagrant - just want to make sure that is correct!

**Pull request merged**
