### PR TITLE
Enable CORS for Rogue's API.

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
Enable CORS for Rogue's API.

#### How should this be reviewed?
👀 

#### Relevant tickets
Fixes first checkbox in [this](https://www.pivotaltracker.com/n/projects/2019429/stories/163460749) Pivotal Card.

#### How to deploy
https://github.com/DoSomething/rogue/blob/master/docs/development/deployments.md

### CODE REVIEW

**Comment by DFurnes** [comment]
@chloealee Can you confirm that this works on your local? I'm not sure that this package does anything unless you apply [this middleware](https://github.com/barryvdh/laravel-cors#global-usage) to some routes (for example, [how we do this](https://github.com/DoSomething/northstar/pull/797) in Northstar).

**Comment by chloealee** [comment]
I think it is working, @DFurnes ! Here's what I got when doing the same thing:
screen shot 2019-02-19 at 1 09 09 pm

I think it works since it is already in the Kernel file [here](https://github.com/DoSomething/rogue/blob/master/app/Http/Kernel.php#L44)?

**Comment by chloealee** [comment]
oh wait! I might just close this PR since [Rogue already has this package](https://github.com/DoSomething/rogue/pull/618/files)?

**Comment by DFurnes** [comment]
Oh, okay cool! Yeah, this should already be good then. 👍

**Comment by chloealee** [comment]
sounds good! Thanks @DFurnes !

**Pull request merged**
