### PR TITLE
Adds Frontend Updates to Posts So It's Easier to Review/Debug

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
-Adds Frontend Updates to Posts So It's Easier to Review/Debug: 
  - Adds `signup_id` to the inbox on the post
  - Adds `signup_source` to the inbox on the post
  - Clarify that `source` on the post right now is the `post_source`
  - Adds a line between the posts

screen shot 2018-04-18 at 5 44 18 pm

#### How should this be reviewed?
👀 

#### Relevant tickets
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156290535) Pivotal Card.

#### How to deploy
https://github.com/DoSomething/rogue/blob/master/docs/development/deployments.md

### CODE REVIEW

**Comment by lkpttn** [comment]
@chloealee Can we pad the line a little bit with like 2x spacer's worth on both sides? There should be a decent gap between posts.

**Comment by chloealee** [comment]
@lkpttn totally! How is this?
screen shot 2018-04-19 at 3 50 05 pm

**Comment by lkpttn** [comment]
@chloealee 👍 👍 👍 👍

**Comment by chloealee** [comment]
@sbsmith86 sorry I linked to the wrong one - I meant #679 !

**Pull request merged**
