### PR TITLE
Restructuring Rogue's Directory Structure 

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
- Moves all v2 and web controllers, transformers, services, repositories, requests, and tests under a `Legacy` folder (v2 lives under the `Two` folders and web lives under the `Web` folders).
- Moves all v3 controllers, transformers, services, repositories, requests, and tests to the root level and deletes the `Three` folder. 

#### How should this be reviewed?
- Might be easiest to go commit by commit.
- All tests should pass!
- Is there anything else I'm missing? 
- Everything should still work like nothing changed! 

#### Relevant tickets
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156139031) Pivotal Card.

#### How to deploy
https://github.com/DoSomething/rogue/blob/master/docs/development/deployments.md

### CODE REVIEW

**Comment by DFurnes** [comment]
screen shot 2018-03-30 at 5 04 05 pm

**Comment by chloealee** [comment]
@DFurnes 😂 I know it is a BEAST! Sorry!!! 😬

**Comment by DFurnes** [comment]
Hehehe, it's super exciting though!! Much cleaner! 🍃

**Comment by sbsmith86** [comment]
Yay! This is looking great to me. Glad tests are passing!

**Comment by chloealee** [comment]
@sbsmith86 yes! And did a smoke test on my local and everything is working as far as I can tell too! :)

**Pull request merged**
